services:
  - type: web
    name: drbleou-hybrid-trading
    runtime: python
    plan: free
    region: oregon
    autoDeploy: true

    # Étapes d'installation et de lancement
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      # --- Configuration Python ---
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: STREAMLIT_SERVER_ENABLECORS
        value: "false"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"

      # --- Sécurité API (⚠️ à remplir toi-même sur Render) ---
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSPHRASE
        sync: false

      # --- Telegram Bot (alertes drawdown/liquidation) ---
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

      # --- Base de données SQLite/SQLAlchemy ---
      - key: DB_URL
        value: "sqlite:///data/trades.db"

      # --- Paramètres de stratégie par défaut ---
      - key: STRATEGY_MODE
        value: "hybrid"             # ou momentum / meanrevert
      - key: DEFAULT_TIMEZONE
        value: "UTC"
      - key: OPTIMIZATION_WINDOW
        value: "9hTU-15hTU"        # heures US à optimiser
      - key: DEFAULT_LEVERAGE
